# Network configuration for different Omne networks

# Mainnet Configuration
[networks.mainnet]
name = "mainnet"
id = 1
genesis_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
commerce_block_time = 3
security_block_time = 540
min_validator_stake = 100
max_validators = 1000
bootstrap_peers = [
    "/dns4/mainnet-boot1.omne.network/tcp/30303",
    "/dns4/mainnet-boot2.omne.network/tcp/30303",
    "/dns4/mainnet-boot3.omne.network/tcp/30303"
]

# Testnet Configuration  
[networks.testnet]
name = "testnet"
id = 2
genesis_hash = "0x1111111111111111111111111111111111111111111111111111111111111111"
commerce_block_time = 3
security_block_time = 540
min_validator_stake = 10
max_validators = 100
bootstrap_peers = [
    "/dns4/testnet-boot1.omne.network/tcp/30303",
    "/dns4/testnet-boot2.omne.network/tcp/30303"
]

# Development Network Configuration
[networks.devnet]
name = "devnet"
id = 3
genesis_hash = "0x2222222222222222222222222222222222222222222222222222222222222222"
commerce_block_time = 3
security_block_time = 60
min_validator_stake = 1
max_validators = 10
bootstrap_peers = [
    "/ip4/127.0.0.1/tcp/30303"
]
